[mypy]
mypy_path = stubs
explicit_package_bases = true
exclude = examples
warn_unused_ignores = true
warn_redundant_casts = true
warn_unreachable = true
warn_unused_configs = true
local_partial_types = true


# libraries without expected type annotations
[mypy-sklearn,sklearn.*]
ignore_missing_imports = true
[mypy-torchvision,torchvision.*]
ignore_missing_imports = true
[mypy-goldener,goldener.*]
ignore_missing_imports = true
[mypy-transformers,transformers.*]
ignore_missing_imports = true
[mypy-datasets,datasets.*]
ignore_missing_imports = true
[mypy-segmentation_models_pytorch,segmentation_models_pytorch.*]
follow_untyped_imports  = true
[mypy-any_gold,any_gold.*]
follow_untyped_imports  = true
[mypy-iterstrat,iterstrat.ml_stratifiers.*]
follow_untyped_imports  = true
[mypy-k_means_constrained,k_means_constrained.*]
follow_untyped_imports  = true
