defaults:
  - _self_

goldener_config:
  min_pxt_insert_size: 10000
  batch_size: 32
  num_workers: 15
  table_name: cifar10_dinov3large_224
  update_selection: True
  update_batch: True
  n_clusters: 0
  n_clusters_batcher: null

exp:
  split_method: all  # Options: random, gold, or all
  batch_method: random  # Options: random, gold, or all
  model: cnn # cnn, resnet, vit
  val_ratio: 0.3
  max_epochs: 50
  learning_rate: 0.001
  batch_size: 256
  validate_on_test: True
  random_state: 42
  checkpoint: checkpoints

data:
  cache: .data
  remove_ratio: null
  drop_duplicate_table: True
  duplicate_table_path: null
  to_duplicate_clusters: null
  cluster_count: null
  duplicate_per_sample: null
  random_split_state: 42
  random_shuffle_state: 42
  num_workers: 15

logging:
  mlflow_tracking_uri: mlruns
  mlflow_experiment_name: cifar10
  mlflow_run_name: cifar10

debug_count:
  test_count: null  # Set to a number (e.g., 5) to limit validation/test batches for debugging. null = no limit
  train_count: null  # Set to a number (e.g., 10) to limit training batches for debugging. null = no limit

hydra:
  job_logging:
    version: 1
