defaults:
  - _self_

goldener_config:
  min_pxt_insert_size: 20000
  batch_size: 32
  num_workers: 8
  table_name: voc_seg_dinov3large_224
  update_selection: True
  update_batch: True
  n_clusters: 0

exp:
  split_method: all  # Options: random, gold, or all
  batch_method: random  # Options: random, gold, or all
  model: unet # deeplab, fpn
  val_ratio: 0.3
  max_epochs: 60
  learning_rate: 0.0001
  batch_size: 16
  validate_on_test: True
  random_state: 42
  checkpoint: checkpoints
  load_from_run_id: null

data:
  cache: /home/ubuntu/gold-splitter-examples/image_segmentation_pascal_voc/.data
  remove_ratio: null
  drop_duplicate_table: True
  duplicate_table_path: null
  to_duplicate_clusters: null
  cluster_count: null
  duplicate_per_sample: null
  random_split_state: 42
  random_shuffle_state: 42
  num_workers: 8

logging:
  mlflow_tracking_uri: mlruns
  mlflow_experiment_name: voc_segmentation
  mlflow_run_name: voc_seg

debug_count:
  test_count: null  # Set to a number (e.g., 5) to limit validation/test batches for debugging. null = no limit
  train_count: null  # Set to a number (e.g., 10) to limit training batches for debugging. null = no limit

hydra:
  job_logging:
    version: 1
